# ================================
# GODOFREDA PROMETHEUS CONFIGURATION
# ================================
# Configuração de monitoramento e métricas
# ================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'godofreda'

# ================================
# RULE FILES
# ================================
rule_files:
  - "rules/*.yml"

# ================================
# SCRAPE CONFIGURATIONS
# ================================
scrape_configs:
  # ================================
  # PROMETHEUS SELF-MONITORING
  # ================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # ================================
  # GODOFREDA API
  # ================================
  - job_name: 'godofreda-api'
    static_configs:
      - targets: ['godofreda-api:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  # ================================
  # GRAFANA
  # ================================
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scrape_interval: 30s

  # ================================
  # ALERTMANAGER
  # ================================
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    metrics_path: /metrics
    scrape_interval: 30s

  # ================================
  # LOKI
  # ================================
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: /metrics
    scrape_interval: 30s

  # ================================
  # PROMTAIL
  # ================================
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
    metrics_path: /metrics
    scrape_interval: 30s

  # ================================
  # NODE EXPORTER (SYSTEM METRICS)
  # ================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 30s

# ================================
# ALERTING
# ================================
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093 